# Generated by Django 5.0.6 on 2025-07-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_borrowing_borrower_email_borrowing_borrower_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='borrower_email',
        ),
        migrations.RemoveField(
            model_name='borrowing',
            name='borrower_name',
        ),
        migrations.RemoveField(
            model_name='borrowing',
            name='borrower_phone',
        ),
        migrations.RemoveField(
            model_name='borrowing',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Librarian'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
