# Generated by Django 5.0.6 on 2025-07-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_librarian_member_remove_borrowing_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
    ]
